"""
BMAD-EVO TypeScript Generator
Phase 2.5 - 自动生成 TypeScript 类型定义
"""

import os
from typing import List, Dict, Optional
from pathlib import Path

from api_contract.types import NormalizedSchema, FieldInfo, FieldType
from api_contract.type_mapper import TypeMapper


class TypeScriptGenerator:
    """
    TypeScript 类型生成器
    
    将 Python Pydantic Model 转换为 TypeScript Interface/Type
    """
    
    def __init__(self, output_dir: str = "", naming_convention: str = "camelCase"):
        """
        初始化生成器
        
        Args:
            output_dir: 输出目录
            naming_convention: 命名约定 (camelCase | snake_case)
        """
        self.output_dir = output_dir
        self.naming_convention = naming_convention
        self.type_mapper = TypeMapper()
    
    def generate_from_schema(self, schema: NormalizedSchema) -> str:
        """
        从单个 Schema 生成 TypeScript Interface
        
        Args:
            schema: 标准化的 Schema
            
        Returns:
            TypeScript 代码字符串
        """
        lines = []
        
        # 添加描述注释
        if schema.description:
            lines.append(f"/** {schema.description} */")
        
        # Interface 定义
        lines.append(f"export interface {schema.name} {{")
        
        # 字段
        for field_name, field in schema.fields.items():
            ts_type = self._convert_field_type(field)
            ts_field_name = self._convert_field_name(field_name)
            
            # 可选标记
            optional_mark = "?" if not field.required else ""
            
            # 字段注释
            if field.description:
                lines.append(f"  /** {field.description} */")
            
            lines.append(f"  {ts_field_name}{optional_mark}: {ts_type};")
        
        lines.append("}")
        
        return "\n".join(lines)
    
    def generate_from_schemas(self, schemas: List[NormalizedSchema]) -> str:
        """
        从多个 Schema 生成 TypeScript 代码
        
        Args:
            schemas: Schema 列表
            
        Returns:
            TypeScript 代码字符串
        """
        lines = [
            "// Auto-generated by BMAD-EVO TypeScript Generator",
            f"// Generated at: {__import__('datetime').datetime.now().isoformat()}",
            "",
        ]
        
        for i, schema in enumerate(schemas):
            lines.append(self.generate_from_schema(schema))
            
            # 空行分隔
            if i < len(schemas) - 1:
                lines.append("")
        
        return "\n".join(lines)
    
    def generate_and_save(
        self, 
        schemas: List[NormalizedSchema], 
        output_file: Optional[str] = None
    ) -> str:
        """
        生成并保存 TypeScript 文件
        
        Args:
            schemas: Schema 列表
            output_file: 输出文件路径（默认自动生成）
            
        Returns:
            生成的文件路径
        """
        content = self.generate_from_schemas(schemas)
        
        if output_file is None:
            output_file = os.path.join(
                self.output_dir or ".", 
                "generated-types.ts"
            )
        
        # 确保目录存在
        os.makedirs(os.path.dirname(output_file) or ".", exist_ok=True)
        
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return output_file
    
    def _convert_field_type(self, field: FieldInfo) -> str:
        """转换字段类型为 TypeScript 类型"""
        original_type = field.original_type or field.field_type.value
        
        # 使用 type_mapper 转换
        ts_type = self.type_mapper.python_to_typescript(original_type)
        
        # 处理可选类型的特殊情况
        if field.nullable and not ts_type.endswith('|undefined'):
            ts_type = f"{ts_type} | null"
        
        return ts_type
    
    def _convert_field_name(self, name: str) -> str:
        """转换字段名称"""
        if self.naming_convention == "camelCase":
            return self._snake_to_camel(name)
        return name
    
    def _snake_to_camel(self, name: str) -> str:
        """snake_case → camelCase"""
        if '_' not in name:
            return name
        parts = name.split('_')
        return parts[0] + ''.join(word.capitalize() for word in parts[1:])


class TypeScriptUpdateManager:
    """
    TypeScript 类型更新管理器
    
    支持增量更新，只变更修改的部分
    """
    
    def __init__(self, output_dir: str):
        self.output_dir = output_dir
        self.cache_file = os.path.join(output_dir, ".bmad-ts-cache.json")
    
    def should_update(self, schema: NormalizedSchema) -> bool:
        """检查 Schema 是否需要更新"""
        # 读取缓存
        cache = self._load_cache()
        
        schema_key = f"{schema.source_file}:{schema.name}"
        cached_hash = cache.get(schema_key)
        
        # 计算当前 hash
        current_hash = self._calculate_hash(schema)
        
        return cached_hash != current_hash
    
    def update_cache(self, schema: NormalizedSchema):
        """更新缓存"""
        cache = self._load_cache()
        
        schema_key = f"{schema.source_file}:{schema.name}"
        cache[schema_key] = self._calculate_hash(schema)
        
        self._save_cache(cache)
    
    def _load_cache(self) -> Dict:
        """加载缓存"""
        import json
        
        if not os.path.exists(self.cache_file):
            return {}
        
        try:
            with open(self.cache_file, 'r') as f:
                return json.load(f)
        except:
            return {}
    
    def _save_cache(self, cache: Dict):
        """保存缓存"""
        import json
        
        os.makedirs(os.path.dirname(self.cache_file) or ".", exist_ok=True)
        
        with open(self.cache_file, 'w') as f:
            json.dump(cache, f, indent=2)
    
    def _calculate_hash(self, schema: NormalizedSchema) -> str:
        """计算 Schema 的 hash"""
        import hashlib
        
        # 基于字段计算 hash
        field_data = []
        for name, field in sorted(schema.fields.items()):
            field_data.append(f"{name}:{field.original_type}:{field.required}")
        
        content = "|".join(field_data)
        return hashlib.md5(content.encode()).hexdigest()


# 便捷函数
def generate_typescript_types(
    schemas: List[NormalizedSchema],
    output_file: str = "generated-types.ts"
) -> str:
    """
    便捷函数：生成 TypeScript 类型
    
    Args:
        schemas: Schema 列表
        output_file: 输出文件路径
        
    Returns:
        生成的文件路径
    """
    generator = TypeScriptGenerator()
    return generator.generate_and_save(schemas, output_file)
